### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by RichardTrouve** [RichardTrouve/displacement_wizard#1]
- [x] Use Maya default connections for 2dplacement file node creation 
cmds.defaultNavigation(connectToExisting=True, source=uv , destination=file_node)

- [ ] Add redshift setup support
- [x] Add "Non-destructive and interactive workflow" setup (texturingXYZ method)
- [ ] Add auto Tex file creation for Renderman UDIM setup (at least find a better solution)
- [x] Add automated Min Max luminance value query for TIFF
- [x] Add automated Min Max luminance value query for EXR (compile OpenExr pyth lib for maya 2017/2018 ,current version is incompatible)
- [x] Add automated Min Max luminance value query for UDIM mode
- [ ] Add zbrush subdivision input slider to estimate optimal mesh subdivision on render 
- [ ] use map resolution to estimate optimal mesh subdivision on render
